included new version of Jsonm to fix stack overflow
oxheadalpha/TZComet pull request #80
Opened 2022-01-06 23:27 UTC by marklnichols

Jsonm module copied from github.com/hhugo/jsonm.git (branch: jsoo-friendly). This fixes the stack overflow error from parsing large objects in JSOO.

2022-01-07 18:09 UTC, smondet requested changes

2022-01-07 18:09 UTC, smondet commented on src/client/dune
> +  (flags --no-inline --pretty))
I don't think we want `--pretty` all the time (maybe we should set a "debug" build mode at some point).

2022-01-07 18:09 UTC, smondet commented on src/client/main.ml
> +  Stdlib.output_string Stdlib.stdout ("Done." ^ "\n")
maybe this could be added to one of the (or _to a new_) examples in `deploy-examples` (not necessarily in this MR)

2022-01-07 18:09 UTC, smondet commented on src/client/tzcomet_jsonm.mli
> +(* Distributed under the ISC license, see terms at the end of the file. *)
I think we should document somewhere (here in the header, or better in the README) where this module comes from (repository / branch / commit-hash).

2022-01-19 19:54 UTC, marklnichols commented on src/client/dune
> +  (flags --no-inline --pretty))
Ok, removing for now

2022-01-19 19:55 UTC, marklnichols commented on src/client/main.ml
> +  Stdlib.output_string Stdlib.stdout ("Done." ^ "\n")
Yeah, this could be part of the development mode examples

2022-01-19 19:56 UTC, marklnichols commented on src/deploy-examples/dune
> +  (pps js_of_ocaml-ppx))
That was probably part of the very poorly thought testing I was doing...removing it.

2022-01-19 20:23 UTC, marklnichols commented on src/client/tzcomet_jsonm.mli
> +(* Distributed under the ISC license, see terms at the end of the file. *)
Ok, put into the README

2022-01-19 21:17 UTC, smondet approved these changes

2022-01-19 21:35 UTC, smondet commented
Pushed to staging:

https://tzcomet.io/#/explorer%3Fexplorer-input%3DKT1WwEZ98PyXu6BqGrDVBZJYbzCRUbPduuT8

![screenshot-20220119-163354](https://user-images.githubusercontent.com/617111/150217376-212a6a05-a03d-44d3-a1bc-1d8fc08efa25.png)

https://tzcomet.io/staging/#/explorer%3Fexplorer-input%3DKT1WwEZ98PyXu6BqGrDVBZJYbzCRUbPduuT8

![screenshot-20220119-163436](https://user-images.githubusercontent.com/617111/150217457-7159cdb5-5fbb-4489-a0c4-63b013660e2f.png)

This fixes #60 (and #62).

2022-01-19 21:51 UTC, merged